name: Keep Alive

on:
  workflow_dispatch:
  schedule:
    - cron: "*/11 * * * *"

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping service
        run: curl -X GET https://aurexa-fastify.onrender.com/ping
